title: This is my page
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my description.
  

show_excerpts: false # set to false to remove excerpts on the homepage

theme: jekyll-theme-tactile
